- src: CSCfi.apache
- src: CSCfi.shibboleth-sp
- src: Stouts.rabbitmq
- src: cchurch.virtualenv
- src: geerlingguy.certbot
- src: geerlingguy.git
- src: geerlingguy.memcached
- src: geerlingguy.pip
- src: geerlingguy.postgresql
- src: geerlingguy.redis
- src: geerlingguy.repo-epel
- src: geerlingguy.supervisor
- src: singleplatform-eng.users
